In [397]:
import pandas as pd
import numpy as np

#### Import data from excel file

In [398]:
df = pd.read_excel("data.xlsx")
print(df)

         X      Z
0    0.500  2.150
1    4.325  2.225
2    8.545  3.192
3   13.180  4.533
4   17.830  6.291
5   21.150  7.146
6   24.480  7.575
7   28.160  7.263
8   32.395  6.147
9   36.150  4.658
10  42.595  2.572
11  49.000  2.160


#### Create band matrix

In [399]:
A = np.zeros((len(df), len(df)))
A[0][0:2] = [2, 1]
for row, column in zip(range(1, len(df)-1, 1), range(0, len(df))):
    A[row][column:column+3] = [1, 4 , 1]
    row +=1
    column += 1
A[len(df)-1][len(df)-2:len(df)] = [1, 2]
print(A)

[[2. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 4. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 4. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 4. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 4. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 4. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 4. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 4. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 4. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 4. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 4. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 2.]]


#### Create geomatric matrix

In [400]:
B = np.zeros((12, 2))
for point in range(2, len(df)):
    point = len(df)+1-point
    B[point-1][0:2] = np.dot(3,[df["X"][point]-df["X"][point-2], 3*(df["Z"][point]-df["Z"][point-2])])
print(B)

[[  0.      0.   ]
 [ 24.135   9.378]
 [ 26.565  20.772]
 [ 27.855  27.891]
 [ 23.91   23.517]
 [ 19.95   11.556]
 [ 21.03    1.053]
 [ 23.745 -12.852]
 [ 23.97  -23.445]
 [ 30.6   -32.175]
 [ 38.55  -22.482]
 [  0.      0.   ]]


#### Calculate tengent vector matrix

In [401]:
T = np.dot(np.linalg.inv(A), B)
print(T)

[[-2.88324288 -0.83804705]
 [ 5.76648576  1.67609411]
 [ 3.95229985  3.51167063]
 [ 4.98931484  5.04922339]
 [ 3.9454408   4.18243581]
 [ 3.13892195  1.73803336]
 [ 3.44887139  0.42143073]
 [ 4.09559247 -2.3707563 ]
 [ 3.91375872 -3.79040553]
 [ 4.21937265 -5.91262159]
 [ 9.80875067 -4.73410812]
 [-4.90437534  2.36705406]]
